# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "private_ip_addresses": "privateIpAddresses",
    "public_ip_addresses": "publicIpAddresses",
    "ssh_keys": "sshKeys",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "privateIpAddresses": "private_ip_addresses",
    "publicIpAddresses": "public_ip_addresses",
    "sshKeys": "ssh_keys",
}
